<html>
    <head>
        <title>
            lydPlayer - Login
        </title>
        <link rel = "stylesheet" type = "text/css" href = "style.css" />
    </head>
    <body>
        <div id="login-wrapper">
            <div id="login-container" class="rounded-corners">
                <div id="notice"></div>
                <form id="login" action="index.php" method="POST">
                    <center>
                        <label for="fusername"/>Username: <input type="text" id="fusername" name="fusername" />
                        <label for="fpassword"/>Password:&nbsp;&nbsp;<input type="password" id="fpassword" name="fpassword" />
                        <input type="submit" />
                    </center>
                </form>
            </div>
        </div>
    </body>
</html>